# Generated by Django 3.1.7 on 2021-04-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyname', models.CharField(max_length=100)),
                ('facultyid', models.CharField(max_length=100)),
                ('dateawarded', models.DateField(default=None, max_length=8, null=True)),
                ('awardname', models.CharField(max_length=100)),
                ('awarddescription', models.TextField(max_length=500)),
                ('department', models.CharField(choices=[('1', 'CSE'), ('2', 'ECE'), ('3', 'EEE'), ('4', 'MECH'), ('5', 'CIVIL')], max_length=100)),
                ('awardedby', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Eventsat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyname', models.CharField(max_length=100)),
                ('facultydesig', models.CharField(max_length=100)),
                ('facultydep', models.CharField(choices=[('1', 'CSE'), ('2', 'ECE'), ('3', 'EEE'), ('4', 'MECH'), ('5', 'CIVIL')], max_length=100, null=True)),
                ('eventtype', models.CharField(choices=[('1', 'International Conference'), ('2', 'PSG CARE Program'), ('3', 'Workshop'), ('4', 'Online Course')], max_length=100)),
                ('confname', models.CharField(max_length=100)),
                ('confby', models.CharField(max_length=100)),
                ('confdesc', models.TextField(max_length=500)),
                ('carename', models.CharField(max_length=100)),
                ('careby', models.CharField(max_length=100)),
                ('caredesc', models.TextField(max_length=500)),
                ('workname', models.CharField(max_length=100)),
                ('workby', models.CharField(max_length=100)),
                ('workdesc', models.TextField(max_length=500)),
                ('cname', models.CharField(max_length=100)),
                ('cby', models.CharField(max_length=100)),
                ('cdesc', models.TextField(max_length=500)),
                ('venue', models.CharField(max_length=100)),
                ('date', models.DateField(default=None, max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eventscon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventtitle', models.CharField(max_length=100)),
                ('eventtype', models.CharField(choices=[('1', 'Faculty Development Program'), ('2', 'Department Association Activites'), ('3', 'Value Added Courses Conducted'), ('4', 'Guest Lecture Conducted'), ('5', 'Workshop Conducted')], max_length=100)),
                ('rpname', models.CharField(max_length=100)),
                ('rpdesig', models.CharField(max_length=100)),
                ('rpcompany', models.CharField(max_length=100)),
                ('rpphone', models.CharField(max_length=15)),
                ('rpmail', models.EmailField(max_length=100)),
                ('organizer', models.CharField(max_length=100)),
                ('date', models.DateField(default=None, max_length=8, null=True)),
                ('nofac', models.CharField(max_length=6)),
                ('nostud', models.CharField(max_length=6)),
                ('dept', models.CharField(choices=[('1', 'CSE'), ('2', 'ECE'), ('3', 'EEE'), ('4', 'MECH'), ('5', 'CIVIL')], max_length=100)),
                ('eventdesc', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyname', models.CharField(max_length=100)),
                ('facultyid', models.CharField(max_length=100)),
                ('annaid', models.CharField(max_length=100)),
                ('aicteid', models.CharField(max_length=100)),
                ('emailid', models.EmailField(max_length=100)),
                ('mobileno', models.CharField(max_length=15)),
                ('dob', models.DateField(default=None, max_length=8, null=True)),
                ('address', models.TextField(max_length=500, null=True)),
                ('bgroup', models.CharField(choices=[('1', 'B+ve'), ('2', 'B-ve'), ('3', 'A+ve'), ('4', 'A-ve'), ('5', 'O+ve'), ('6', 'O-ve'), ('7', 'AB+ve'), ('8', 'AB-ve')], max_length=6, null=True)),
                ('department', models.CharField(choices=[('1', 'CSE'), ('2', 'ECE'), ('3', 'EEE'), ('4', 'MECH'), ('5', 'CIVIL')], max_length=100, null=True)),
                ('ugabout', models.TextField(max_length=500, null=True)),
                ('ugyear', models.CharField(max_length=4, null=True)),
                ('pgabout', models.TextField(max_length=500, null=True)),
                ('pgyear', models.CharField(max_length=4, null=True)),
                ('phdabout', models.TextField(max_length=500, null=True)),
                ('phdyear', models.CharField(max_length=4, null=True)),
                ('ac_name', models.CharField(max_length=100, null=True)),
                ('ac_from', models.DateField(default=None, max_length=8, null=True)),
                ('ac_to', models.DateField(default=None, max_length=8, null=True)),
                ('in_name', models.CharField(max_length=100, null=True)),
                ('in_from', models.DateField(default=None, max_length=8, null=True)),
                ('in_to', models.DateField(default=None, max_length=8, null=True)),
                ('re_name', models.CharField(max_length=100, null=True)),
                ('re_from', models.DateField(default=None, max_length=8, null=True)),
                ('re_to', models.DateField(default=None, max_length=8, null=True)),
                ('aoi', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
