# Generated by Django 3.1.7 on 2021-05-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyid', models.CharField(max_length=100)),
                ('eventtitle', models.CharField(max_length=100)),
                ('eventtype', models.CharField(choices=[('1', 'Faculty Development Program'), ('2', 'Department Association Activites'), ('3', 'Value Added Courses Conducted'), ('4', 'Guest Lecture Conducted'), ('5', 'Workshop Conducted')], max_length=100)),
                ('rpname', models.CharField(max_length=100, null=True)),
                ('rpdesig', models.CharField(max_length=100, null=True)),
                ('rpcompany', models.CharField(max_length=100, null=True)),
                ('rpphone', models.CharField(max_length=15, null=True)),
                ('rpmail', models.EmailField(max_length=100, null=True)),
                ('organizer', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(default=None, max_length=8, null=True)),
                ('nofac', models.CharField(max_length=6, null=True)),
                ('nostud', models.CharField(max_length=6, null=True)),
                ('dept', models.CharField(choices=[('1', 'CSE'), ('2', 'ECE'), ('3', 'EEE'), ('4', 'MECH'), ('5', 'CIVIL')], max_length=100)),
                ('eventdesc', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eveat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyid', models.CharField(max_length=100)),
                ('facultyname', models.CharField(max_length=100)),
                ('facultydesig', models.CharField(max_length=100, null=True)),
                ('facultydep', models.CharField(choices=[('1', 'CSE'), ('2', 'ECE'), ('3', 'EEE'), ('4', 'MECH'), ('5', 'CIVIL')], max_length=100, null=True)),
                ('eventtype', models.CharField(choices=[('1', 'International Conference'), ('2', 'PSG CARE Program'), ('3', 'Workshop'), ('4', 'Online Course')], max_length=100)),
                ('eventname', models.CharField(max_length=100, null=True)),
                ('eventby', models.CharField(max_length=100, null=True)),
                ('eventdesc', models.CharField(max_length=100, null=True)),
                ('venue', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(default=None, max_length=8, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Eventsat',
        ),
        migrations.DeleteModel(
            name='Eventscon',
        ),
        migrations.AlterField(
            model_name='awards',
            name='awarddescription',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='awards',
            name='awardedby',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='emailid',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='mobileno',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
