# Generated by Django 3.2.3 on 2021-05-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_audio_store'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Audio_store',
            new_name='Audio',
        ),
    ]
