# Generated by Django 3.2.3 on 2021-05-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_audio_store_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
