# Generated by Django 3.2.3 on 2021-05-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210531_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=1000)),
                ('my_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
