# Generated by Django 3.2.3 on 2021-05-31 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210531_1722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files1',
            new_name='File',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='filename',
            new_name='file_name',
        ),
    ]
